/* =====================================================================
   Steve's Financial Report Dashboard — PROD prerequisite (DB)
   Create + seed  Workbench.dbo.ProposalOriginalRep  (attribution overrides)

   The dashboard LEFT JOINs this table on ProposalID and COALESCEs the original
   seller over the current rep. Missing table => runtime error; missing/partial
   rows => silently wrong CFO attribution. So this script is fail-closed + atomic.

   Hardened per crew review (Kimi K3 / Gemini 3.1 Pro / gpt-5.6-sol), 2026-07-21:
     - SET XACT_ABORT ON + single transaction  -> no partial seed
     - THROW (not RAISERROR) on precondition/asserts -> deploy stops on failure
     - UNIQUE index on ProposalID -> no double-count via the LEFT JOIN
     - hard row-count assert (563) -> truncation/transit loss fails the deploy
     - backs up any pre-existing prod table before reseeding (rollback)
     - dropped 1 bad override (ProposalID 396441, OrigRepName 'UNDEFINED') that
       would have EXCLUDED that proposal from the dashboard. 564 -> 563 clean rows.

   ProposalIDs are shared identity with prod (play is a ~24h replica of prod).
   Requires: the Workbench DB on prod (already used by the V1.5 SalesGoal deploy)
   AND that the GSTS ColdFusion datasource login can SELECT this table (see STEP 4).
   ===================================================================== */
SET NOCOUNT ON;
SET XACT_ABORT ON;   -- any error aborts the batch and rolls back the open transaction

-- STEP 0: preconditions (fail closed) ---------------------------------
IF DB_ID('Workbench') IS NULL
  THROW 50001, 'Workbench database not found on this server — it is required (used by the V1.5 dashboards).', 1;
GO
USE Workbench;
GO

-- STEP 1: backup any pre-existing table (one-time; preserves original for rollback)
IF OBJECT_ID('dbo.ProposalOriginalRep') IS NOT NULL
   AND OBJECT_ID('dbo.ProposalOriginalRep_bak_predeploy') IS NULL
BEGIN
  SELECT * INTO dbo.ProposalOriginalRep_bak_predeploy FROM dbo.ProposalOriginalRep;
END;
GO

-- STEP 2: create table + UNIQUE index if missing
IF OBJECT_ID('dbo.ProposalOriginalRep') IS NULL
  CREATE TABLE dbo.ProposalOriginalRep (
    ProposalID  int          NOT NULL,
    CurRepID    int          NULL,
    OrigRepName varchar(101) NULL,
    Source      varchar(32)  NOT NULL,
    Conflict    int          NOT NULL
  );
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='ux_por_ProposalID' AND object_id=OBJECT_ID('dbo.ProposalOriginalRep'))
  CREATE UNIQUE NONCLUSTERED INDEX ux_por_ProposalID ON dbo.ProposalOriginalRep (ProposalID);
GO

-- STEP 3: atomic re-seed ---------------------------------------------
BEGIN TRANSACTION;
DELETE FROM dbo.ProposalOriginalRep;
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (382340,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (382347,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (382358,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (382370,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (382372,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (382373,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (382374,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (382375,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (382376,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (382377,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (382378,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (383544,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (386339,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (387913,1143,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (390800,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (390957,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (393897,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (395839,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (395851,1143,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (397363,1142,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (397364,1142,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (397365,1142,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (398133,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (403775,1143,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (404424,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (404761,1143,'Patrick Fringer','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (406041,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (406219,1142,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (406667,1142,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (407526,1142,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (407527,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (407529,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (407530,1142,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (407533,1142,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (407540,1142,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (407714,1142,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (407728,1143,'Patrick Fringer','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (407861,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (407953,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (408027,1142,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (408034,1142,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (409283,1142,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (409284,1142,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (409288,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (409289,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (409290,1142,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (409294,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (409295,1142,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (409367,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (412569,1143,'Patrick Fringer','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (412577,1143,'Patrick Fringer','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (412582,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (417169,1143,'Adam Hubbard','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (418765,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (418796,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (418799,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (418805,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (419118,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (419121,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (419122,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (419123,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (419195,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (419203,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (419401,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (419403,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (419409,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (419423,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (419436,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (419448,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (419505,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (420086,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (420832,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (421271,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (423114,1143,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (424407,1143,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (424409,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (427952,1143,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (427953,1143,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (434345,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (434406,1143,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (436936,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (438797,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (444250,1143,'Patrick Fringer','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (444254,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (446840,1142,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (446841,1142,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (447061,1142,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (447408,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (448145,1143,'Patrick Fringer','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (448417,1142,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (449319,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (449320,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (451965,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (452151,1143,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (452204,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (452243,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (452259,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (452263,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (453467,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (453471,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (453610,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (453687,1142,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (454546,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (454936,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (454938,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (456034,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (468098,1142,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (468106,1142,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (470360,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (470362,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (470372,1143,'Patrick Fringer','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (470390,1143,'Patrick Fringer','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (471910,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (473469,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (482349,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (482352,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (482702,1143,'Jeff Melin','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (485650,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (490776,1143,'Patrick Fringer','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (491966,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (492962,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (492964,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (492975,1142,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (496996,1143,'Patrick Fringer','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (498279,1143,'Patrick Fringer','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (498280,1143,'Patrick Fringer','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (498282,1143,'Patrick Fringer','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (498283,1143,'Patrick Fringer','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (500330,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (500334,1143,'Jeff Melin','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (500362,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (500666,1143,'Patrick Fringer','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (502273,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (502494,1143,'Jeff Melin','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (503154,1143,'Jeff Melin','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (504615,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (508667,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (515662,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (515838,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (516801,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (516802,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (521513,1142,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (527238,1142,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (527526,1142,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (535204,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (535206,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (542944,1143,'Adam Hubbard','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (542945,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',1);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (543612,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (543632,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (544684,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (546347,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (546348,1143,'Stephen Darden','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (546376,1143,'Stephen Darden','snapshot(HistoricalProjectOwner)',1);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (548601,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (548603,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (548664,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (548665,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (548671,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (548723,1143,'Jeff Melin','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (548725,1143,'Jeff Melin','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (548750,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (548932,1143,'Jeff Melin','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (548966,1143,'Jeff Melin','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (549791,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (551224,1142,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (551301,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (552188,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (553585,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',1);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (553627,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (553630,1143,'Adam Hubbard','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (555111,1142,'Adam Hubbard','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (556578,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (557629,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (557631,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (557632,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (567475,1143,'Stephen Darden','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (568604,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (568893,1142,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (569261,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (570256,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',1);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (570299,1143,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (570301,1143,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (570309,1143,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (570320,1143,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (570337,1143,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (570537,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (570542,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (572376,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (572378,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (572382,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (572472,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (574638,1142,'Adam Hubbard','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (574943,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (575597,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (576070,1143,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (577945,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (577947,1143,'Adam Hubbard','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (578066,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (578140,1143,'Adam Hubbard','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (579134,1143,'Parker Keil','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (579172,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (579249,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (579272,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (579492,1143,'Stephen Darden','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (579493,1143,'Stephen Darden','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (579519,1143,'Stephen Darden','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (579522,1143,'Stephen Darden','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (580571,1143,'Stephen Darden','snapshot(HistoricalProjectOwner)',1);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (581554,1143,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (581556,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (581602,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (581663,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (582194,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (588232,1143,'Stephen Darden','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (590622,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (591853,1143,'Parker Keil','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (592519,1143,'Parker Keil','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (593599,1143,'Parker Keil','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (594035,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (594062,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (598343,1143,'Parker Keil','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (598439,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (598612,1143,'Parker Keil','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (598629,1143,'Parker Keil','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (598633,1143,'Parker Keil','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (598652,1143,'Parker Keil','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (598820,1143,'Parker Keil','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (598825,1143,'Parker Keil','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (598835,1143,'Parker Keil','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (598844,1143,'Parker Keil','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (598852,1142,'Moy Salinas','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (598945,1143,'Parker Keil','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (598947,1143,'Parker Keil','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (598951,1143,'Parker Keil','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (598994,1142,'Moy Salinas','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (599285,1142,'Moy Salinas','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (599453,1142,'Moy Salinas','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (599461,1142,'Moy Salinas','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (599476,1142,'Moy Salinas','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (599588,1142,'Moy Salinas','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (599620,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (599695,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (599709,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (599741,1142,'Moy Salinas','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (599743,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (599746,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (599748,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (599750,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (599761,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (599792,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (600262,1142,'Moy Salinas','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (600280,1142,'Moy Salinas','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (600293,1142,'Moy Salinas','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (600440,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (600441,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (600442,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (600452,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (601490,1142,'Moy Salinas','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (602835,1143,'Parker Keil','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (602896,1143,'Parker Keil','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (605008,1143,'Parker Keil','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (605415,1142,'Kirk Hinshaw','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (610410,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (610411,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (610858,1142,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (611644,1143,'Stephen Darden','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (611835,1143,'Stephen Darden','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (611986,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (611987,1143,'Parker Keil','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (612240,1143,'Stephen Darden','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (612244,1143,'Scott Andre','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (612277,1143,'Chase Schroeder','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (614309,1143,'Stephen Darden','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (614496,1143,'Chase Schroeder','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (614501,1143,'Chase Schroeder','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (614548,1143,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (620742,1143,'Stephen Darden','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (620776,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (620791,1143,'Stephen Darden','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (620845,1143,'Stephen Darden','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (620846,1143,'Stephen Darden','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (620905,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',1);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (621241,1143,'Stephen Darden','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (621243,1143,'Stephen Darden','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (621690,1142,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (621828,1143,'Stephen Darden','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (621831,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (621871,1143,'Garrett Cornish','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (621934,1143,'Stephen Darden','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (622064,1143,'Stephen Darden','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (622678,1143,'Scott Andre','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (626666,1143,'Garrett Cornish','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (627086,1143,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (627087,1143,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (627245,1142,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (628472,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (632996,1142,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (633377,1143,'Stephen Darden','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (635650,1143,'Stephen Darden','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (635684,1143,'Stephen Darden','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (635696,1143,'Stephen Darden','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (635729,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (636475,1143,'Stephen Darden','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (638938,1143,'Chase Schroeder','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (639956,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (640356,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (641895,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (642266,1143,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (642443,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (643636,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (644225,1143,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (644233,1142,'Scott Griffiths','snapshot(HistoricalProjectOwner)',1);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (644409,1143,'Garrett Cornish','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (644538,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (651213,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (651639,1142,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (655628,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (655854,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (664739,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (670665,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (672332,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (675147,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (677391,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (677447,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (683884,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (686267,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (686300,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (690540,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (690541,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (690542,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (690663,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (690664,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (690665,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (690669,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (690711,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (690712,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (690757,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (690758,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (690811,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (690812,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (690853,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (690854,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (690856,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (692101,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (692102,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (692240,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (692241,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (692254,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (692255,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (692273,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (692274,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (692343,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (692344,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (692366,1143,'Patrick Fringer','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (692738,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (693023,1143,'Chase Schroeder','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (693025,1143,'Chase Schroeder','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (693031,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (693085,1143,'Chase Schroeder','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (693086,1143,'Nathan Nevois','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (693755,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (699054,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (701506,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (701507,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (702062,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (702063,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (705325,1143,'Garrett Cornish','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (709255,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (709556,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (709568,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (710647,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (710723,1143,'Nathan Nevois','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (712466,1140,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (712566,1140,'Nathan Nevois','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (717662,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (717664,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (717671,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (717692,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (717693,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (718763,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (718764,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (721234,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (721235,1143,'Scott Griffiths','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (721248,1143,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (721281,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (721313,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (721335,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (721345,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (721346,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (721354,1140,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (721419,1143,'Chris Mello','commission',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (721784,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (721789,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (722245,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (722337,1143,'Chris Mello','commission',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (726348,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (726352,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (726411,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (726501,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (726506,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (726507,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (726599,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (726602,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (726800,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (726801,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (726877,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (726879,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (726986,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (727193,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (728296,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (728297,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (728355,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (728358,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (728498,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (728869,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (728870,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (728896,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (728897,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (728898,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (729015,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (729102,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (729258,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (729259,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (729264,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (729265,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (729266,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (729275,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (729280,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (729281,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (729317,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (729324,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (729332,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (729339,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (729394,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (729396,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (729512,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (729518,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (729526,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (729530,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (730220,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (730327,1140,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (730828,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (731021,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (731022,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (731034,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (731039,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (731045,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (731047,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (731052,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (731053,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (731085,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (731086,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (731143,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (731167,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (731168,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (731173,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (731174,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (731178,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (731179,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (731181,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (731182,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (731214,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (731238,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (731250,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (731261,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (735511,1143,'Jeremy Indes','snapshot(HistoricalProjectOwner)',1);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (735608,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (736817,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (736921,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (736953,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (736955,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (737265,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (737267,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (738658,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (738660,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (745069,1140,'Jeremy Indes','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (748186,1143,'Chris Mello','commission',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (754119,1143,'Chris Mello','commission',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (755816,1143,'Chris Mello','commission',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (755865,1143,'Former (reassigned)','Former',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (755867,1143,'Former (reassigned)','Former',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (755978,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (755995,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (756355,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (756676,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (756899,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (758137,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (758202,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (758329,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (759647,1143,'Chris Mello','commission',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (760083,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (760512,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (761016,1140,'Chase Schroeder','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (761189,1140,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (761228,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (761306,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (761308,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (761462,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (761463,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (761464,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (761478,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (761491,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (761549,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (761792,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (761860,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (764154,1143,'Former (reassigned)','Former',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (764155,1143,'Former (reassigned)','Former',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (764270,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (764352,1143,'Former (reassigned)','Former',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (764353,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (764506,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (764507,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (767914,1143,'Chris Mello','commission',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (767934,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (767940,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (767971,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (767976,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (768087,1143,'Former (reassigned)','Former',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (768126,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (768349,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (768649,1143,'Chase Schroeder','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (768698,1143,'Chase Schroeder','commission',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (768732,1143,'Chase Schroeder','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (768733,1143,'Chase Schroeder','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (768734,1143,'Chase Schroeder','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (774469,1140,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (774575,1143,'Chase Schroeder','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (775628,1143,'Former (reassigned)','Former',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (775629,1143,'Former (reassigned)','Former',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (776066,1143,'Former (reassigned)','Former',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (776068,1143,'Former (reassigned)','Former',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (776069,1143,'Garrett Cornish','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (776132,1143,'Garrett Cornish','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (776135,1143,'Garrett Cornish','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (777275,1140,'Chase Schroeder','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (777477,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (777632,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (783683,1143,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (783856,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (785431,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (785540,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (785548,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (785639,1143,'Toby Henry','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (786080,1143,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (788036,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (788337,1143,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (788514,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (788516,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (790130,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (790149,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (790150,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (790327,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (790387,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (790388,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',1);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (790391,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (790392,1143,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (790465,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (790466,1143,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (790480,1143,'Chris Mello','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (791050,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (791073,1143,'Scott Griffiths','RFP',0);
INSERT INTO Workbench.dbo.ProposalOriginalRep (ProposalID,CurRepID,OrigRepName,Source,Conflict) VALUES (791076,1143,'Chris Mello','snapshot(HistoricalProjectOwner)',0);

-- hard assert: exactly 563 rows or the whole deploy rolls back
IF (SELECT COUNT(*) FROM dbo.ProposalOriginalRep) <> 563
  THROW 50002, 'Seed row count != 563 — rolling back (transit/truncation loss).', 1;

COMMIT TRANSACTION;
GO

/* STEP 4 (REQUIRED — Jordan/IT): the GSTS ColdFusion datasource login must be able to
   SELECT this table. On prod the CF login may be scoped to the gsts DB only; grant it:
       GRANT SELECT ON Workbench.dbo.ProposalOriginalRep TO [<GSTS_CF_DATASOURCE_LOGIN>];
   (Use the actual SQL login the prod GSTS datasource connects as. If that login is db_owner
    / sysadmin, this is already covered — confirm rather than assume.)                        */

-- final verify (expect 563)
SELECT COUNT(*) AS RowCount_expect_563 FROM dbo.ProposalOriginalRep;
